name: Create Endpoint and Deploy Model to Endpoint Workflow

on:
  workflow_dispatch:

jobs:
  create_endpoint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Python version 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Azure ML SDK
      run: |
        python -m pip install azureml-sdk
    - name: Create Endpoint
      run: |
        az ml online-endpoint create --name mslearn-mlops-v1-endpoint -f src/create-endpoint.yml --resource-group TestResourceGroup --workspace-name dreams-aml
  deploy_to_endpoint:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python version 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Azure ML SDK
        run: |
          python -m pip install azureml-sdk
      - name: Deploy Model to Endpoint
        run: |
          az ml online-deployment create --name mslearn-mlops-v1-deployed --endpoint-name mslearn-mlops-v1-endpoint --file src/deploy-model-to-endpoint.yml --resource-group TestResourceGroup --workspace-name dreams-aml
