name: Deploy Model to Endpoint Workflow

on:
  workflow_dispatch:

jobs:
  deploy_to_endpoint:
      runs-on: ubuntu-latest
#      needs: create_endpoint
      steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy Model to Endpoint
        run: |
          az ml online-deployment create --name mslearn-mlops-v1-deployed --endpoint mslearn-mlops-v1-endpoint -f src/deploy-model-to-endpoint.yml --resource-group TestResourceGroup --workspace-name dreams-aml --all-traffic
